
factors = []
rs = []

in_preamble = True
for line in open("c02minus.txt"):
    if in_preamble:
        if line.startswith("   n  #Fac"):
            in_preamble = False
        continue
    n, _, facs = line.split()
    r = 2**int(n) - 1
    hexr = "{:x}".format(r)
    hexrparts = ["0x{}".format(hexr[::-1][i:i+16][::-1].rjust(16, "0"))
                 for i in range(0, len(hexr), 16)][::-1]
    rs.append(hexrparts)
    intfacs = [int(fac.split("^")[0]) for fac in facs.split(".")]
    outfacs = []
    for intfac in intfacs:
        ratio = r // intfac
        hexfac = "{:x}".format(ratio)
        hexfacparts = ["0x{}".format(hexfac[::-1][i:i+16][::-1].rjust(16, "0"))
                       for i in range(0, len(hexfac), 16)][::-1]
        outfacs.append(hexfacparts)
    factors.append(outfacs)

with open("factors_data.rs", "w") as f:
    f.write("// This file autogenerated by factors2rs.py, do not edit.\n\n")
    f.write("pub static FACTORS: [&[&[u64]]; 512] = [\n")
    for (idx, ratios) in enumerate(factors):
        f.write("    &[\n")
        f.write("        &[{}],\n".format(", ".join(rs[idx])))
        for ratioparts in ratios:
            f.write("        &[{}],\n".format(", ".join(ratioparts)))
        f.write("    ],\n")
    f.write("];\n\n")
